// GENERATED by packages/contracts/scripts/record-addresses.mjs from
// packages/contracts/deployments/<chainId>.json. Do not edit: an address
// typed here is one that can disagree with the chain it names.

export type Deployment = {
  chainId: number;
  /** MandateRegistry. */
  registry: string;
  /** TreeVault, the only funding source. */
  vault: string;
  /** ConductRecord, which writes into the ERC-8004 reputation registry. */
  record: string;
  /** The block the contracts were made in. Reading from zero fails on
   *  Arc — the RPC answers `pruned history unavailable` — so anything
   *  that queries logs starts here, including the browser. */
  fromBlock: string;
  /** The commit the deploy script ran from. */
  commit: string;
  deployedAt: string;
};

export const DEPLOYMENT: Deployment | null = {
  chainId: 5042002,
  registry: "0x5a0a521cd083a3e884dc024c90898589751292b8",
  vault: "0x6a37c9506740d4d59e343cbbf8d7c2f56aa112eb",
  record: "0xa8bcdda003cddfb672a33e23a0bb375b6bed4a9f",
  fromBlock: "62518670",
  commit: "unknown",
  deployedAt: "2026-09-17T04:42:39.908Z",
};
