// GENERATED by packages/mcp/scripts/emit-tools.ts, by asking a running
// server what it exposes. Do not edit. A tool that fails to register
// disappears from here, which is the point.

export const MCP_TOOLS = [
  {
    "name": "pactra_fetch",
    "args": "url, method?, body?",
    "note": "Fetch a URL. If it answers 402, pay for it through Pactra and return the body. The recipient and the price come from the seller's own challenge, not from you. May return a refusal, which is final."
  },
  {
    "name": "pactra_spawn",
    "args": "label, budgetUsdc, trancheUsdc?, concentrationPct?",
    "note": "Register a child mandate under this one for a sub-agent. The child can only ever be narrower than its parent; the contract refuses a wider one whoever asks. The key for the child is held here, not by any agent."
  },
  {
    "name": "pactra_status",
    "args": "no arguments",
    "note": "What this mandate may still spend, and which node in the tree is the limit. The answer is often an ancestor rather than this node."
  }
] as const;

/** The tools that will never exist. The absence is the argument, and it
 *  is asserted against the same server in packages/mcp/test. */
export const ABSENT_TOOLS = [
  "pactra_transfer",
  "pactra_pay",
  "pactra_send",
  "pactra_withdraw",
  "pactra_approve"
] as const;

/** The block to paste into an MCP client. Its environment is the one the
 *  daemon actually reads — see ENV in packages/daemon/src/config.ts. */
export const MCP_CONFIG = "{\n  \"mcpServers\": {\n    \"pactra\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"pactra-mcp\"\n      ],\n      \"env\": {\n        \"PACTRA_ENV_FILE\": \"pactra.env\",\n        \"PACTRA_MCP_NODE\": \"0x… — the node this server speaks for\"\n      }\n    }\n  }\n}";

export const MCP_ENV = {
  "required": {
    "PACTRA_VAULT": "TreeVault address, from deployments/<chainId>.json",
    "PACTRA_REGISTRY": "MandateRegistry address, from the same file",
    "PACTRA_NODE_<label>": "the mandate node this daemon acts for",
    "PACTRA_KEY_<label>": "the operator key for that node. The agent never sees it"
  },
  "optional": {
    "PACTRA_RECORD": "ConductRecord, from deployments/<chainId>.json. Without it, refusals are enforced but never published",
    "PACTRA_IDENTITY": "ERC-8004 Identity; defaults to 0x8004A818BFB912233c491871b3d84c89A494BD9e",
    "PACTRA_RPC": "defaults to https://rpc.testnet.arc.io",
    "PACTRA_CHAIN_ID": "defaults to 5042002",
    "PACTRA_USDC": "the 6-decimal ERC-20 view; defaults to Arc's",
    "PACTRA_NETWORKS": "CAIP-2 ids this daemon will settle on",
    "PACTRA_ASSETS": "assets it will pay in",
    "PACTRA_PORT": "defaults to 8402",
    "PACTRA_POLL_MS": "receipt polling interval; defaults to 250, matched to Arc's finality rather than to viem's 4,000",
    "PACTRA_KEY_FILE": "where a spawned child's key is written, before the spawn is sent; defaults to ~/.pactra/pactra.env"
  }
} as const;
